openapi: 3.0.1
info:
  title: Culture Amp Public API
  description: This Open API specification describes the interface for the Culture Amp public API service
  contact:
    name: Culture Amp Support
    email: support@cultureamp.com
  license:
    name: CultureAmp
  version: 0.0.1
servers:
  - url: https://api.cultureamp.com/v1
    description: Production
  - url: https://sandbox.public-api.development.cultureamp.net/v1
    description: Development
tags:
  - name: Employees
  - name: Performance
  - name: Surveys
paths:
  /employees:
    get:
      tags:
        - Employees
      summary: List employees
      description: |-
        Returns all employees in the account.

        If both `email` and `employee_identifier` are provided, `employee_identifier` will take precedence.

        `cursor` is optional and used for pagination.
      operationId: list-employees
      security:
        - Oauth2:
            - employees-read
  "/employees/{id}":
    get:
      tags:
        - Employees
      summary: Get employee
      description: Returns the details of an employee corresponding to the provided Culture Amp employee identifier
      operationId: get-employee
      security:
        - Oauth2:
            - employees-read
  "/employees/{id}/demographics":
    get:
      tags:
        - Employees
      summary: List demographics by employee
      description: Returns the demographic assignments for a given employee
      operationId: list-demographics-by-employee
      security:
        - Oauth2:
            - employee-demographics-read
  "/employees/{id}/manager-reviews":
    get:
      tags:
        - Performance
      summary: List manager reviews by employee
      description: Returns manager reviews for a given employee
      operationId: list-manager-reviews-by-employee
      security:
        - Oauth2:
            - performance-evaluations-read
  /performance-cycles:
    get:
      tags:
        - Performance
      summary: List performance cycles
      description: |-
        Returns all performance cycles in the account.

        If both `cursor` and `state` are provided in a request, `cursor` takes precedence.
      operationId: list-performance-cycles
      security:
        - Oauth2:
            - performance-evaluations-read
  "/performance-cycles/{id}":
    get:
      tags:
        - Performance
      summary: Get performance cycle
      description: Returns the details of a performance cycle by its id
      operationId: get-performance-cycle
      security:
        - Oauth2:
            - performance-evaluations-read
  "/performance-cycles/{id}/manager-reviews":
    get:
      tags:
        - Performance
      summary: List manager reviews by performance cycle
      description: Returns manager reviews for a given performance cycle
      operationId: list-manager-reviews-by-performance-cycle
      security:
        - Oauth2:
            - performance-evaluations-read
  /manager-reviews:
    get:
      tags:
        - Performance
      summary: List manager reviews
      description: Returns all manager reviews in the account
      operationId: list-manager-reviews
      security:
        - Oauth2:
            - performance-evaluations-read
  "/manager-reviews/{id}":
    get:
      tags:
        - Performance
      summary: Get manager review
      description: Returns the details of a manager review corresponding to the provided id
      operationId: get-manager-review
      security:
        - Oauth2:
            - performance-evaluations-read
  "/surveys":
    get:
      tags:
        - Surveys
      summary: List surveys
      deprecated: true
      description: |
        Returns a list of all surveys in the account

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: list-surveys
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{id}":
    get:
      tags:
        - Surveys
      summary: Get survey
      deprecated: true
      description: |
        Retrieves the details of an individual survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: get-survey
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{id}/questions":
    get:
      tags:
        - Surveys
      summary: List questions
      deprecated: true
      description: |
        Returns a list of all questions from an individual survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: list-survey-questions
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{survey_id}/question/{question_id}":
    get:
      tags:
        - Surveys
      summary: Get question
      deprecated: true
      description: |
        Retrieves the details of an individual question from a survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: get-survey-question
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{id}/responses":
    get:
      tags:
        - Surveys
      summary: List responses
      deprecated: true
      description: |
        Returns a list of all responses from an individual survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: list-survey-responses
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{survey_id}/responses/{response_id}":
    get:
      tags:
        - Surveys
      summary: Get response
      deprecated: true
      description: |
        Retrieves the details of an individual response from a survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: get-survey-response
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{id}/factors":
    get:
      tags:
        - Surveys
      summary: List factors
      deprecated: true
      description: |
        Returns a list of all factors from an individual survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: list-survey-factors
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{survey_id}/factors/{factor_id}":
    get:
      tags:
        - Surveys
      summary: Get factor
      deprecated: true
      description: |
        Retrieves the details of an individual factor from a survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: get-survey-factor
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{id}/sections":
    get:
      tags:
        - Surveys
      summary: List sections
      deprecated: true
      description: |
        Returns a list of all sections from an individual survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: list-survey-sections
      security:
        - Oauth2:
            - surveys-read
  "/surveys/{survey_id}/sections/{section_id}":
    get:
      tags:
        - Surveys
      summary: Get section
      deprecated: true
      description: |
        Retrieves the details of an individual section from a survey

        > 🛑 Deprecated API - No Longer Available
        >
        > This API is no longer available to setup. Please use the [Reporting API](https://support.cultureamp.com/en/articles/9232738-reporting-api) for access to RDE enabled Survey data which is available now.
      operationId: get-survey-section
      security:
        - Oauth2:
            - surveys-read
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /oauth2/token
          scopes:
            employees-read: Grants read access to employees resources
            employee-demographics-read: Grants access to employee demographics
            performance-evaluations-read: Grants access to employee performance evaluations
# Turns off 'Try It' feature in the Developer Portal